Bring in a collection of commits addressing the new location.
pulumiverse/pulumi-vra pull request #1
Opened 2022-10-04 17:53 UTC by schmidtw

2022-10-04 20:04 UTC, ringods requested changes

2022-10-04 20:04 UTC, ringods commented on provider/resources.go
> +			RootNamespace: "pulumiverse",
.NET namespaces are usually capitalized. Can you update this?

2022-10-04 20:25 UTC, ringods commented
@schmidtw in `resources.go`, you map everything in `index` (constant: `mainMod`). Can you have a look if you can group a subset of the resources and functions into different modules?

Have a read up on this issue on what I mean with this:
https://github.com/pulumiverse/pulumi-heroku/issues/1

2022-10-04 22:39 UTC, schmidtw commented
> @schmidtw in `resources.go`, you map everything in `index` (constant: `mainMod`). Can you have a look if you can group a subset of the resources and functions into different modules?
> 
> Have a read up on this issue on what I mean with this: [pulumiverse/pulumi-heroku#1](https://github.com/pulumiverse/pulumi-heroku/issues/1)

Yes and thanks for the suggestion.  I had initially split things out, but thought I was over-thinking the API since it was so small.  I'll adjust them.

2022-10-04 23:51 UTC, ringods commented
@schmidtw I don't know about the VRA specifics, so I leave this mainly up to you. 

Though, I invite you to look at it from the perspective of the user of your VRA provider: what would make sense for this person when they know the VRA product terminology? Is the module and class naming "fluent" to use?

Changing this mapping later on results in breaking changes in the generated SDKs, which is something to prevent.

2022-10-05 03:51 UTC, schmidtw commented
> @schmidtw I don't know about the VRA specifics, so I leave this mainly up to you.
> 
> Though, I invite you to look at it from the perspective of the user of your VRA provider: what would make sense for this person when they know the VRA product terminology? Is the module and class naming "fluent" to use?
> 
> Changing this mapping later on results in breaking changes in the generated SDKs, which is something to prevent.

I spent a fair bit of time trying to find the right combination of modules.  This ([5717df3](https://github.com/pulumiverse/pulumi-vra/pull/1/commits/5717df3dd0270b475f5400d387763c9d657daf83)) seems as reasonable as I can come up with & I'm sticking with that.

I was able to query a few things, create a VM and delete the VM so I think this code is working ok.  I'm completely new to VRA.

2022-10-06 15:14 UTC, ringods commented on .github/workflows/release.yml
> +  PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
This needs to be `${{ secrets.PYPI_PASSWORD }}`

2022-10-07 16:56 UTC, ringods approved these changes

2022-10-07 21:16 UTC, merged